### ISSUE TITLE
Can't get script to work - cookie not set

### ISSUE THREAD

**Issue by rocksuicide** [medius/utm_form#1]
Hi - this is a great idea and actually (should) perfectly solve a problem i've been facing recently. However, after installing it I can't get it to work!
I'm not 100% what the cookie is called that it should be setting, but I can't see one i don't recognise in developer tools. Also, the forms fields I've added to my lead capture form don't appear to be getting populated either.
A couple questions:
1. What is the cookie called that should get set?
2. Does the script add the new fields to the form itself, or do they need to be there in the first place?
3. If you already have the fields in the form and you're using custom field names (because their generated by a CMS for example) and in the script code the custom form field names are set, does the script handle a situation where not all the fields are present (i'm only really interested in campaign, source and medium at present, so they're the only ones i've added to my form)

Thanks in advance for you help!

P.S. There is a missing closing quote from the script source attribute in the last code example in your readme.md file. I'd change it and issue a pull request but I've no idea how this stuff works! sorry.

**Comment by rocksuicide** [comment]
Should probably add, this is inside a site made with Drupal, hosted on Pantheon. the form in question is a node creation form.

**Comment by medius** [comment]
To answer your questions:
1) There are several cookies: They all start with "_uc_". Here's the current list: 
- _uc_utm_source
- _uc_utm_medium
- _uc_utm_campaign
- _uc_utm_content
- _uc_utm_term
- _uc_referrer
- _uc_last_referrer
- _uc_initial_landing_page
- _uc_visits
- _uc_current_session

There are also helper functions to access these in the script if you are so inclined. You could also use a [chrome extension](https://chrome.google.com/webstore/detail/editthiscookie/fngmhnnpilhplaeedifhccceomclgfbg?hl=en) to see all the values.

2) The script adds the new fields itself and you don't need to add them. 
3) Since the script adds the fields to the form, it will add them based on what cookie is present. If a relevant cookies is not saved (e.g utm_content was not passed), then it is not added to the form.

The only thing that you need to do is configure your CMS to be able to accept the fields you want and ignore the rest.

Hope this helps.

**Comment by medius** [comment]
Closing this issue since it seems to be addressed.
